update QuickLRU option (2)
StarpTech/apollo-datasource-http pull request #21
Opened 2021-11-16 02:26 UTC by shkaper

Following up on #15, I've fixed the flaking test there. I think sinonjs FakeTimer is a more robust solution for a test where timeouts are involved.

Closes #14

2021-11-16 02:31 UTC, shkaper commented on test/http-data-source.test.ts
> +test.serial('Global maxAge should be used when no maxAge was set or similar.', async (t) => {
using `serial()` here because otherwise FakeTimers mess up the timeouts in concurrent tests

2021-12-13 02:23 UTC, shkaper commented
Hey @StarpTech, have you got the chance to review this yet?

2021-12-13 09:34 UTC, StarpTech requested changes

2021-12-13 09:34 UTC, StarpTech commented on src/http-data-source.ts
> +      maxAge: this.options?.lru?.maxAge,
Apollo works with seconds. Should we work with seconds too here?

2021-12-27 20:12 UTC, thiagomini commented
Hi @shkaper and @StarpTech , we are in need of this feature as well. Cna you merge this and update the package?

2021-12-27 21:01 UTC, StarpTech commented
Hi @thiagomini, the PR is reviewed, but the original author isn't responding. In the future, I recommend creating a separate PR. I'll handle it for now.

2021-12-27 21:04 UTC, merged